apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ggx84t8y6-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ggx84t8y6-go 
  name: ggx84t8y6-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ggx84t8y6-go 
